### ISSUE TITLE
multiple payments for one subscription

### ISSUE THREAD

**Issue by kelvinmakau444** [IanWambai/Chowder#15]
Hi thanks for the good work. i am using the Chowder but i have one concern, what if there is this scenario where the customer wants to pay monthly subscription once say for 5 months.

**Comment by IanWambai** [comment]
Hi @kelvohh , sorry I didn't get a notification for this.

If you mean _pay once a month for 5 months_: The first time a user pays store the date of the next expected payment on your database. The date can be a month, or 5 months, or whatever period of time you would like. Every time the user opens your app, or tries to access a certain feature, check if the next expected payment date is before or after today. If it's after, then the month hasn't ended and you can let the user access the feature. If it's before today then the user's subscription has expired, and you show them a payment page, they click something like "Make Payment", then you call Chowder to do the rest. If the payment is successful, store the next payment date to replace the previous one.

I've implemented a basic version of this that uses SharedPreferences. I'd recommend you store the data on a server instead of locally though, because if the user uninstalls your app and reinstalls in, all the payment information is lost.

**Comment by kelvinmakau444** [comment]
thanks for your feedback Ian,  i will try to implement the logic.  however
i have one problem though, the sample and my app worked once but now when i
try to test a payment it sticks at "wait for a popup from Safaricom" which
never appears. But when i put another number the popup appears successfully
on the other device. Iam using your test credentials,,  What could be the
problem.
